title: "찌니블로그"
description: "찌니의 프로그래밍 공부 블로그"
url: "https://ziniblog.github.io"
permalink: /post/:title
tag_order: [leetcode,dev]

markdown: kramdown
kramdown:
    syntax_highlighter_opts:
        disable: true